##load("@rules_cc//cc:defs.bzl", "cc_test")  #load the test target

cc_test(
    name = "mma_test",
    size = "small",
    srcs = ["mma_test.cc"],
    deps = [
        "@gtest//:gtest_main",
        "//lib:utils_lib",
        "//lib:memory_manager_lib",
        ],
    copts = [
        "-std=c++11",
    ],
    linkopts = [
        "-pthread",
    ],
)

cc_test(
    name = "q1",
    size = "small",
    srcs = ["q1.cc"],
    deps = [
        "@gtest//:gtest_main",
        "//lib:utils_lib",
        "//lib:memory_manager_lib",
        ],
    copts = [
        "-std=c++11",
    ],
    linkopts = [
        "-pthread",
    ],
)

cc_test(
    name = "q2",
    size = "small",
    srcs = ["q2.cc"],
    deps = [
        "@gtest//:gtest_main",
        "//lib:utils_lib",
        "//lib:memory_manager_lib",
        ],
    copts = [
        "-std=c++11",
    ],
    linkopts = [
        "-pthread",
    ],
)

cc_test(
    name = "q3",
    size = "small",
    srcs = ["q3.cc"],
    deps = [
        "@gtest//:gtest_main",
        "//lib:utils_lib",
        "//lib:memory_manager_lib",
        ],
    copts = [
        "-std=c++11",
    ],
    linkopts = [
        "-pthread",
    ],
)

cc_test(
    name = "q4",
    size = "small",
    srcs = ["q4.cc"],
    deps = [
        "@gtest//:gtest_main",
        "//lib:utils_lib",
        "//lib:memory_manager_lib",
        ],
    copts = [
        "-std=c++11",
    ],
    linkopts = [
        "-pthread",
    ],
)